
set(MUSE_APP_NAME_HUMAN_READABLE "Sada")
set(MUSE_APP_NAME_MACHINE_READABLE "Sada")

set(MUSE_APP_NAME_HUMAN_READABLE_COMPAT "Sada")
set(MUSE_APP_NAME_MACHINE_READABLE_COMPAT "Sada")

set(MUSE_APP_VERSION_MAJOR "4")
set(MUSE_APP_VERSION_MINOR "0")
set(MUSE_APP_VERSION_PATCH "0")
set(MUSE_APP_VERSION_MAJ_MIN "${MUSE_APP_VERSION_MAJOR}.${MUSE_APP_VERSION_MINOR}")
set(MUSE_APP_VERSION "${MUSE_APP_VERSION_MAJ_MIN}.${MUSE_APP_VERSION_PATCH}")

set(MUSE_APP_VERSION_LABEL "")

# Sada product version, shown to users. MUSE_APP_VERSION above stays on the Audacity
# base version on purpose: project-file compatibility checks in au3 depend on it.
set(SADA_VERSION_MAJOR "0")
set(SADA_VERSION_MINOR "1")
set(SADA_VERSION_PATCH "0")
set(SADA_VERSION "${SADA_VERSION_MAJOR}.${SADA_VERSION_MINOR}.${SADA_VERSION_PATCH}")
set(SADA_BASE_VERSION_TEXT "Audacity ${MUSE_APP_VERSION}")

set(MUSE_APP_GUI_IDENTIFIER io.github.m3athrazaq.sada)

set(MUSE_APP_TITLE "${MUSE_APP_NAME_HUMAN_READABLE}")
set(MUSE_APP_NAME "${MUSE_APP_NAME_MACHINE_READABLE_COMPAT}")
set(MUSE_APP_TITLE_VERSION "${MUSE_APP_TITLE} ${SADA_VERSION_MAJOR}.${SADA_VERSION_MINOR}")
set(MUSE_APP_NAME_VERSION "${MUSE_APP_NAME} ${SADA_VERSION_MAJOR}.${SADA_VERSION_MINOR}")

set(MUSE_APP_UNSTABLE ON)
set(MUSE_APP_IS_PRERELEASE ON)

# MUSE_APP_RELEASE_CHANNEL is assigned per-mode in SetupConfigure.cmake based on AU4_BUILD_MODE.

message(STATUS "MUSE_APP_VERSION ${MUSE_APP_VERSION}")
